name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.2"]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go 1.22.2
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2
      - name: Build planet-registry
        run: make build
